name: elastic_dashboard
description: A simple and modern dashboard for FRC.
publish_to: 'none'
version: 2025.0.0-beta-4

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  animations: ^2.0.7
  collection: ^1.17.1
  decimal: ^2.3.3
  dot_cast: ^1.2.0
  dropdown_button2: ^2.3.9
  elegant_notification: ^2.2.0
  file_selector: ^1.0.1
  flex_seed_scheme: ^2.0.0
  flutter:
    sdk: flutter
  flutter_box_transform: ^0.4.2
  flutter_colorpicker: ^1.1.0
  flutter_context_menu: ^0.1.3
  flutter_fancy_tree_view: ^1.1.1
  flutter_hooks: ^0.20.0
  flutter_launcher_icons: ^0.13.1
  github: ^9.17.0
  http: ^1.2.0
  import_sorter: ^4.6.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  messagepack: ^0.2.1
  msgpack_dart: ^1.0.1
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.0.15
  patterns_canvas: ^0.4.0
  popover: ^0.3.0
  provider: ^6.0.5
  screen_retriever: ^0.1.9
  searchable_listview: ^2.7.0
  shared_preferences: ^2.1.2
  syncfusion_flutter_charts: ^23.1.44
  syncfusion_flutter_gauges: ^23.1.44
  titlebar_buttons: ^1.0.0
  transitioned_indexed_stack: ^1.0.2
  url_launcher: ^6.1.14
  uuid: ^4.2.2
  vector_math: ^2.1.4
  version: ^3.0.2
  visibility_detector: ^0.4.0+2
  web_socket_channel: ^2.4.3
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/fields/

import_sorter:
  comments: false
  ignored_files:
    - /*.mocks.dart

flutter_launcher_icons:
  image_path: "assets/logos/logo.png"
  windows:
    generate: true
    image_path: "assets/logos/logo.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/logos/logo.png"
  linux:
    generate: true
    image_path: "assets/logos/logo.png"
