name: elastic_dashboard
description: A simple and modern dashboard for FRC.
publish_to: 'none'
version: 2025.2.2

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  animations: ^2.0.11
  collection: ^1.19.1
  decimal: ^3.2.1
  dot_cast: ^1.2.0
  dropdown_button2: ^2.3.9
  elegant_notification: ^2.4.4
  file_selector: ^1.0.3
  flex_seed_scheme: ^3.5.1
  flutter:
    sdk: flutter
  flutter_box_transform: ^0.4.7
  flutter_colorpicker: ^1.1.0
  flutter_context_menu: ^0.2.2
  flutter_fancy_tree_view: ^1.6.0
  flutter_launcher_icons: ^0.14.3
  geekyants_flutter_gauges:
    git:
      url: https://github.com/Gold872/GaugesFlutter.git
      ref: elastic-version
  github: ^9.24.0
  http: ^1.3.0
  import_sorter: ^4.6.0
  intl: ^0.20.2
  logger: ^2.5.0
  messagepack: ^0.2.1
  msgpack_dart: ^1.0.1
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  patterns_canvas: ^0.5.0
  popover: ^0.3.1
  provider: ^6.1.4
  screen_retriever: ^0.2.0
  searchable_listview: ^2.17.0
  shared_preferences: ^2.5.3
  syncfusion_flutter_charts: ^29.1.37+1
  titlebar_buttons: ^1.0.0
  transitioned_indexed_stack: ^1.0.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  vector_math: ^2.1.4
  version: ^3.0.2
  visibility_detector: ^0.4.0+2
  web_socket_channel: ^3.0.2
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/fields/

import_sorter:
  comments: false
  ignored_files:
    - /*.mocks.dart

flutter_launcher_icons:
  image_path: "assets/logos/logo.png"
  windows:
    generate: true
    image_path: "assets/logos/logo.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/logos/logo.png"
  linux:
    generate: true
    image_path: "assets/logos/logo.png"
