name: elastic_dashboard
description: A simple and modern dashboard for FRC.
publish_to: 'none'
version: 2026.0.0-beta-1

environment:
  sdk: '^3.8.0'

dependencies:
  animations: ^2.1.1
  collection: ^1.19.1
  decimal: ^3.2.4
  dot_cast: ^1.2.0
  dropdown_button2: ^2.3.9
  elegant_notification: ^2.5.1
  file_selector: ^1.0.4
  flex_seed_scheme: ^3.6.1
  flutter:
    sdk: flutter
  flutter_box_transform: ^0.4.7
  flutter_colorpicker: ^1.1.0
  flutter_context_menu: ^0.3.0
  flutter_fancy_tree_view: ^1.6.0
  flutter_launcher_icons: ^0.14.4
  geekyants_flutter_gauges:
    git:
      url: https://github.com/Gold872/GaugesFlutter.git
      ref: elastic-version
  github: ^9.25.0
  http: ^1.6.0
  import_sorter: ^4.6.0
  intl: ^0.20.2
  logger: ^2.6.2
  msgpack_dart:
    git:
      url: https://github.com/TheTripleV/msgpack_dart.git
      ref: fix-64-bit-ints
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  patterns_canvas: ^0.5.0
  popover: ^0.4.0
  provider: ^6.1.5+1
  screen_retriever: ^0.2.0
  searchable_listview: ^2.19.3
  shared_preferences: ^2.5.3
  syncfusion_flutter_charts: ^31.2.12
  titlebar_buttons: ^1.0.0
  transitioned_indexed_stack: ^1.0.2
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  vector_math: ^2.2.0
  version: ^3.0.2
  visibility_detector: ^0.4.0+2
  web: ^1.1.1
  web_socket_channel: ^3.0.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.5.1
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf

  assets:
    - assets/logos/
    - assets/fields/
    - assets/third_party_licenses/

import_sorter:
  comments: false
  ignored_files:
    - /*.mocks.dart

flutter_launcher_icons:
  image_path: "assets/logos/logo.png"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
  linux:
    generate: true
  web:
    generate: true
